### ISSUE TITLE
Crash on ChallengeStatusReceiver.protocolError

### ISSUE THREAD

**Issue by komissarovdenis** [Adyen/adyen-3ds2-android#11]
Just trying to simulate a protocol error during challenge flow.

1. Set random data in `ChallengeParameters.acsTransactionID` and `doChallenge` (all other data is correct)
2. Receive an error in callback `protocolError`
3.a if try to close transaction by `transaction.close()` in this method application will immediately chases.

Stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.adyen.threeds2.internal.a.a.b.i.e()' on a null object reference
	at com.adyen.threeds2.internal.a.a.b.a.c.a(Unknown Source:93)
	at com.adyen.threeds2.internal.f.a(Unknown Source:103)
	at com.adyen.threeds2.internal.a.d$2.run(Unknown Source:70)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
3.b in case transaction doesn't closed same method `protocolError` will be called in infinity mode.

The last version of the lib is used: 2.1.0-rc03

**Comment by timon-langlotz** [comment]
Hi @komissarovdenis,

this issue should be fixed with our latest release (2.1.0-rc04).

Cheers!

**Comment by komissarovdenis** [comment]
Hi @timon-langlotz 

Just tried same scenario and if wrap doChallenge in try/catch block it's possible to catch such incorrect params exception. That's fine for me. 

Thanks for quick update :)

**Comment by timon-langlotz** [comment]
Exactly, that's how it should be. In case of any invalid input from your side, you get an `InvalidInputException`.

Cheers!
