### ISSUE TITLE
Invalid challengeParameters when trying to do challenge

### ISSUE THREAD

**Issue by husamk** [Adyen/adyen-3ds2-android#29]
trying to perform a challenge on a test adyen card, but receiving that ChallengeParameters is invalid

`val challengeParameters = ChallengeParameters()
        challengeParameters.set3DSServerTransactionID(threeDSServerTransID)
        challengeParameters.acsTransactionID = acsTransID
        challengeParameters.acsRefNumber = acsReferenceNumber
        challengeParameters.acsSignedContent = acsSignedContent`
        
threeDSServerTransID
        `33edcbd2-162f-4f98-a345-84574af93c4d`

![Screen Shot 2021-03-15 at 10 36 34 PM](https://user-images.githubusercontent.com/37999237/111218110-fe437600-85de-11eb-9790-f5ca8a593476.png)

**Comment by caiofaustino** [comment]
Hi there,

If you set your app to Debug build you should be able to se the cause of it being invalid in the exception message.

**Comment by husamk** [comment]
@caiofaustino nothing more than the following:
com.adyen.threeds2.exception.InvalidInputException: Invalid challengeParameters.
        at atd.y.a.a(:2)
        at com.adyen.threeds2.internal.w.a(:10)
        at com.adyen.threeds2.internal.w.doChallenge(:9)
        at app.getaway.reactModules.visaCardManager.CardManagerModule.performChallenge(CardManagerModule.kt:85)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)

**Comment by caiofaustino** [comment]
Well, please check the contents of the variables you are passing. Variables need to be not null, and  `AcsTransactionID` and `3DSServerTransactionID` need to be a UUID parsed like `UUID.fromString(value)`

**Comment by husamk** [comment]
@caiofaustino this is what we already sending:
3DSServerTransactionID : cafb88ad-bc1e-4659-aa28-95aece67b435
AcsTransactionID : 09c82248-394e-4e29-a428-e5b1e18622cc

I tested both of them and they can be parsed by UUID.fromString(value)

**Comment by husamk** [comment]
will close the ticket
I see that downgrading the version of the SDK to 2.2.0 solves the issue.
