### ISSUE TITLE
Re open issue #30 Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by mikkoville** [Adyen/adyen-3ds2-android#34]
**Describe the bug**
Issue I reported in https://github.com/Adyen/adyen-3ds2-android/issues/30 did not get fixed in the latest version.

Should we reopen the previous issue or keep this new one?

version `2.2.2`
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1703)
       at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1743)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:276)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:228)
       at com.adyen.threeds2.internal.ui.activity.a$a.run(a.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Brand:samsung
Model:Galaxy S21 Ultra 5G
Operating System
Version:11
Rooted:No

**Comment by jreij** [comment]
@mikkoville let's reopen the other one then!
