### ISSUE TITLE
ChallengeActivity - NullPointerException (View.setAlpha(float)' on a null object reference)

### ISSUE THREAD

**Issue by modobosh** [Adyen/adyen-3ds2-android#39]
Our users receive crashes when they try to open a Challange activity (video attached)

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
       at android.view.View$2.setValue(View.java:25788)
       at android.view.View$2.setValue(View.java:25785)
       at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1379)
       at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
       at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:674)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:637)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1069)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1088)
       at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
       at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1081)
       at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1142)
       at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1227)
       at android.animation.AnimatorSet.start(AnimatorSet.java:729)
       at android.animation.AnimatorSet.start(AnimatorSet.java:684)
       at com.adyen.threeds2.internal.ui.activity.a.a(a.java:58)
       at com.adyen.threeds2.internal.ui.activity.a.a(a.java:49)
       at com.adyen.threeds2.internal.ui.activity.a.c(a.java:10)
       at com.adyen.threeds2.internal.ui.activity.a.b(a.java:32)
       at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(ChallengeActivity.java:25)
       at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onNewIntent(ChallengeActivity.java:3)
       at android.app.Activity.performNewIntent(Activity.java:7471)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1387)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1399)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3685)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:3701)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3718)
       at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**To Reproduce**
1. Go to add a payment card
2. Enter test data 
Visa | 4917 6100 0000 0000 | 03/2030 | 737
3. Click on 'Verify'
4. Challenge activity tries to open and then the app crashed

**Video**
[video](https://lebara-my.sharepoint.com/:v:/p/mykhailo_dobosh/EW1nRj7tDLxJlFgiTfXh-60B6BWYlbTrV1TL_R1Tqu7PEg?email=caiofaustino%40gmail.com&e=5UiopO)
**Expected behavior**
Challenge activity is opened without a crash.

**Lib version**
implementation "com.adyen.threeds:adyen-3ds2:2.2.2"

**Smartphone (please complete the following information):**
Different devices
<img width="431" alt="Screenshot 2021-09-02 at 14 41 00" src="https://user-images.githubusercontent.com/89970030/131837480-1e1fee82-3292-4d48-ab0e-0a635eb370ca.png">

**Comment by jreij** [comment]
Hi, we have seen this issue before and the main cause was a 3rd party customization library (e.g. [Beagle](https://github.com/pandulapeter/beagle)) or some code inside your app that modifies the currently visible activity. Can you check if that applies to you?

**Comment by modobosh** [comment]
Hi, thank you for the quick response.
Yes, I found an issue that you mention earlier (https://github.com/Adyen/adyen-android/issues/404), we reviewed the app code and don't found any lib or something else that modifies currently visible activity. 
But we will do it one more time, to be sure that is not our case

let's keep in touch

**Comment by modobosh** [comment]
Hi, a small update:
For our part, we have not yet found any problems associated with the change visibility of current activity.

**Comment by modobosh** [comment]
Hi, we investigate and found that crash was caused by lib https://support.liveassistfor365.com/hc/en-us/articles/360006116734-Live-Assist-for-365-Android-SDK.

Thank you for the advice, the bug can be closed

**Comment by modobosh** [comment]
@jreij One more request from us, whether you can investigate the cause of the problem and ways to solve it from the SDK size, because the problem may occur with other libraries as well.

**Comment by messenger63** [comment]
Hi @jreij, also to rise a ticket for liveassist team, we need to know root cause of issue, as from stacktrace it just crash in Adyen lib, without relation to other libs.

**Comment by caiofaustino** [comment]
@messenger63 could you describe to me what liveassist does and how it interacts with the 3DS2 challenge screen?

**Comment by messenger63** [comment]
@caiofaustino it do not have direct relation to screen, but it initialised in Application class and have access to all activity lifecycle and WindowManager. 

Here is sample of decompiled core class:
```
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package com.alicecallsbob.assist.sdk.core;

import android.app.Activity;
import android.app.Application;
import android.app.Application.ActivityLifecycleCallbacks;
import android.content.Context;
import android.graphics.Point;
import android.os.Bundle;
import android.os.Handler;
import android.os.HandlerThread;
import android.os.Looper;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.webkit.WebView;
import com.alicecallsbob.assist.sdk.aed.AssistAEDListener;
import com.alicecallsbob.assist.sdk.aed.impl.AssistAEDManager;
import com.alicecallsbob.assist.sdk.aed.impl.AssistAEDScreenManager;
import com.alicecallsbob.assist.sdk.config.AssistConfig;
import com.alicecallsbob.assist.sdk.config.impl.AssistAgentCobrowseListener;
import com.alicecallsbob.assist.sdk.config.impl.AssistAnnotationListener;
import com.alicecallsbob.assist.sdk.config.impl.AssistConfigBuilder;
import com.alicecallsbob.assist.sdk.config.impl.AssistConfigImpl;
import com.alicecallsbob.assist.sdk.config.impl.AssistErrorListener.AssistError;
import com.alicecallsbob.assist.sdk.overlay.AssistAnnotationOverlay;
import com.alicecallsbob.assist.sdk.permissions.Agent;
import com.alicecallsbob.assist.sdk.permissions.PermissionChecker;
import com.alicecallsbob.assist.sdk.web.WebViewInputElementsListenerManager;
import com.alicecallsbob.assist.sdk.web.WebViewPermissionsManager;
import com.alicecallsbob.assist.sdk.web.impl.WebViewPermissionsManagerImpl;
import com.alicecallsbob.assist.sdk.window.SharedWindowController;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import org.json.JSONObject;

public class AssistCoreImpl implements AssistAEDListener, AssistCore {
    private static final String TAG = AssistCoreImpl.class.getSimpleName();
    private Activity currentActivity;
    private WindowManager windowManager;
    private AssistAEDManager aedManager;
    private AssistOverlayManager overlayManager;
    private Handler nonUIThreadHandler;
    private Handler uiThreadHandler = new Handler(Looper.getMainLooper());
    private boolean isAssistanceActive = false;
    private AssistConfig lastAssistanceConfig;
    private AssistListenerWrapper listener;
    private List<AssistInternalListener> internalListeners = new ArrayList();
    private WebViewInputElementsListenerManager webViewListenerManager = WebViewInputElementsListenerManager.getInstance();
    private Application application;
    private boolean isApplicationActive = true;
    private boolean assistStopping = false;
    private final LayoutAdjustPanWatcher layoutPanWatcher = new LayoutAdjustPanWatcher();
    private final AssistDocumentShareManagerImpl documentShareManager = new AssistDocumentShareManagerImpl();
    private final WebViewPermissionsManager webViewPermissionsManager;

    public AssistCoreImpl(Application application) {
        this.application = application;
        application.registerActivityLifecycleCallbacks(new AssistCoreImpl.AssistAcitivityLifecycleCallbackHandler());
        this.windowManager = (WindowManager)application.getSystemService("window");
        Point screenSize = new Point();
        this.windowManager.getDefaultDisplay().getSize(screenSize);
        this.overlayManager = new AssistOverlayManager(application.getApplicationContext(), screenSize);
        this.webViewPermissionsManager = new WebViewPermissionsManagerImpl(this);
        HandlerThread thread = new HandlerThread("AssistApplicationThread");
        thread.start();
        this.nonUIThreadHandler = new Handler(thread.getLooper());
    }

    public boolean isApplicationStopping() {
        return this.assistStopping;
    }

    public void terminate() {
        this.overlayManager.dismissOverlays();
    }

    public void stopAssist() {
        Log.i(TAG, "stopAssist() - ending the Assist support.");
        if (this.lastAssistanceConfig != null && this.lastAssistanceConfig.getCobrowseListener() != null) {
            this.lastAssistanceConfig.getCobrowseListener().onCobrowseInactive();
        }

        this.overlayManager.dismissOverlays();
        this.overlayManager.clearAnnotations();
        if (this.aedManager != null) {
            AssistAEDScreenManager screenManager = this.aedManager.getAedScreenManager();
            if (screenManager != null) {
                screenManager.stopScreenSharingService();
            }

            if (this.aedManager.hasConnection()) {
                this.aedManager.closeConnection();
            }

            this.documentShareManager.destroy();
            this.aedManager = null;
        }

        this.internalListeners.clear();
        WebViewInputElementsListenerManager.getInstance().clearWebViewListeners();
        if (this.lastAssistanceConfig != null) {
            this.endAnnotationContext();
        }

        this.isAssistanceActive = false;
        this.assistStopping = false;
    }

    private void endAnnotationContext() {
        AssistAnnotationOverlay annotationOverlay = this.overlayManager.getAnnotationsOverlay();
        final AssistAnnotationListener assistAnnotationListener = this.lastAssistanceConfig.getAnnotationListener();
        if (assistAnnotationListener != null) {
            final AnnotationContextImpl annotationContext = annotationOverlay.getAnnotationContext();
            if (annotationContext != null) {
                annotationContext.destroy();
                Handler uiHandler = new Handler(Looper.getMainLooper());
                uiHandler.post(new Runnable() {
                    public void run() {
                        Log.v(AssistCoreImpl.TAG, "annotationContext ended callback");
                        assistAnnotationListener.annotationContextEnded(annotationContext);
                    }
                });
            }
        }

    }

    public void addInternalListener(AssistInternalListener listener) {
        this.internalListeners.add(listener);
    }

    public void removeInternalListener(AssistInternalListener listener) {
        this.internalListeners.remove(listener);
    }

    private String getAssistLoginCredentials() {
        HashMap<String, String> formData = new HashMap();
        formData.put("username", "user_not_used");
        formData.put("password", "password_not_used");
        return (new JSONObject(formData)).toString();
    }

    public AssistDocumentShareManagerImpl getDocumentShareManager() {
        return this.documentShareManager;
    }

    public void startScreenSharing(AssistConfig config, List<SharedWindowController> sharedWindowControllers) {
        this.aedManager = new AssistAEDManager(this, this, config, this.listener);
        this.documentShareManager.setAedManager(this.aedManager);
        String topicId = config.getCorrelationId();
        this.aedManager.connect(topicId, sharedWindowControllers);
    }

    private boolean isCorrelationMode(AssistConfig config) {
        return config.getAgentName() == null || config.getAgentName().isEmpty();
    }

    private void startAssistanceSession(AssistConfig config) {
        if (this.isAssistanceActive) {
            this.listener.onSupportError(AssistError.SESSION_IN_PROGRESS);
        } else {
            View contentView = ScreenHelper.getContentView(this.currentActivity);
            if (contentView instanceof ViewGroup) {
                List<View> views = new ArrayList();
                ScreenHelper.getChildrenOfView((ViewGroup)contentView, views);
                Iterator var4 = views.iterator();

                while(var4.hasNext()) {
                    View view = (View)var4.next();
                    if (view instanceof WebView) {
                        WebView webView = (WebView)view;
                        this.webViewListenerManager.addSupportedWebView(webView);
                    }
                }
            }

            boolean isCorrelationMode = this.isCorrelationMode(config);
            if (isCorrelationMode) {
                this.startScreenSharing(config, new ArrayList());
            }

            this.overlayManager.showOverlays();
            if (this.overlayManager.getSpotlightOverlay() != null) {
                this.addInternalListener(this.overlayManager.getSpotlightOverlay());
            }

            this.lastAssistanceConfig = config;
            this.isAssistanceActive = true;
        }
    }

    public void startSupport(final AssistConfig config, AssistListener listener) {
        this.listener = new AssistListenerWrapper(config, listener);
        if (!AssistOverlayManager.isOverlayPermissionGranted(this.getApplicationContext())) {
            boolean coBrowseMode = this.isCorrelationMode(config);
            if (!coBrowseMode) {
                this.listener.onSupportError(AssistError.VOICE_AND_VIDEO_PERMISSION_ERROR);
                return;
            }

            this.listener.onSupportError(AssistError.OVERLAY_CREATE_FAILURE);
        }

        if (this.overlayManager.getSpotlightOverlay() != null) {
            this.removeInternalListener(this.overlayManager.getSpotlightOverlay());
        }

        this.overlayManager.resetInitialised();
        this.initOverlayManager();
        if (config.getSessionToken() == null) {
            this.nonUIThreadHandler.post(new Runnable() {
                public void run() {
                    AssistLoginManager.login(config, AssistCoreImpl.this.getAssistLoginCredentials(), new AssistLoginListener() {
                        public void onLoginSuccess(String sessionToken, String userId) {
                            AssistConfigBuilder builder = new AssistConfigBuilder(AssistCoreImpl.this.getApplicationContext(), config);
                            final AssistConfigImpl modifiedConfig = (AssistConfigImpl)builder.build();
                            modifiedConfig.setSessionToken(sessionToken);
                            modifiedConfig.setCorrelationId(userId);
                            AssistCoreImpl.this.uiThreadHandler.post(new Runnable() {
                                public void run() {
                                    AssistCoreImpl.this.startAssistanceSession(modifiedConfig);
                                }
                            });
                        }

                        public void onLoginFailure(String reason) {
                            Log.e(AssistCoreImpl.TAG, "Failed to create consumer session [" + reason + "]");
                            AssistCoreImpl.this.listener.onSupportError(AssistError.SESSION_CREATION_FAILURE);
                        }
                    });
                }
            });
        } else {
            this.startAssistanceSession(config);
        }

    }

    public void endSupport() {
        this.assistStopping = true;
        this.stopAssist();
        if (this.lastAssistanceConfig != null) {
            AssistLoginManager.logout(this.lastAssistanceConfig.getAssistConsumerUrl(), this.lastAssistanceConfig.getSessionToken());
        }

        this.listener.onSupportEnded(true);
    }

    public Class getAssistServiceClass() {
        return AssistService.class;
    }

    public AssistOverlayManager getOverlayManager() {
        return this.overlayManager;
    }

    public WindowManager getWindowManager() {
        return this.windowManager;
    }

    public Activity getCurrentActivity() {
        return this.currentActivity;
    }

    public Context getApplicationContext() {
        return this.application.getApplicationContext();
    }

    public void onOpened() {
        Log.d(TAG, "AssistTransportObserverImpl::onTransportOpened called.");
    }

    public void onAssistMessage(byte[] message) {
        Log.d(TAG, "AssistTransportObserverImpl::onAssistMessage called.");
    }

    private void initOverlayManager() {
        this.overlayManager.init(this.getCurrentActivity());
        this.addInternalListener(this.overlayManager.getSpotlightOverlay());
        this.layoutPanWatcher.setupLayoutPannedWatcher(this.getCurrentActivity());
    }

    public boolean isApplicationActive() {
        return this.isApplicationActive;
    }

    public int getKeyboardAdjustPanYOffset() {
        return this.layoutPanWatcher.getLayoutPannedYOffset();
    }

    public void allowCobrowseForAgent(Agent agent) {
        AssistAEDScreenManager screenManager = this.getAedScreenManager();
        if (screenManager != null) {
            screenManager.allowCobrowseForAgent(agent);
        } else {
            Log.e(TAG, "Unable to allow Agent for cobrowse - Not in session");
        }

    }

    public void disallowCobrowseForAgent(Agent agent) {
        AssistAEDScreenManager screenManager = this.getAedScreenManager();
        if (screenManager != null) {
            screenManager.disallowCobrowseForAgent(agent);
        } else {
            Log.e(TAG, "Unable to disallow Agent for cobrowse - Not in session");
        }

    }

    public void pauseCobrowse() {
        AssistAEDScreenManager screenManager = this.getAedScreenManager();
        if (screenManager != null) {
            screenManager.pauseCobrowse();
        } else {
            Log.e(TAG, "Unable to pause cobrowse - Not in session");
        }

    }

    public void resumeCobrowse() {
        AssistAEDScreenManager screenManager = this.getAedScreenManager();
        if (screenManager != null) {
            screenManager.resumeCobrowse();
        } else {
            Log.e(TAG, "Unable to pause cobrowse - Not in session");
        }

    }

    public void sendConsumerEndSupport() {
        if (this.aedManager != null) {
            this.aedManager.sendConsumerEndSupportMessage();
        }

    }

    private AssistAEDScreenManager getAedScreenManager() {
        if (this.aedManager == null) {
            Log.e(TAG, "AED manager is null");
            return null;
        } else {
            AssistAEDScreenManager screenManager = this.aedManager.getAedScreenManager();
            if (screenManager == null) {
                Log.e(TAG, "AED screen manager is null");
            }

            return screenManager;
        }
    }

    public WebViewPermissionsManager getWebViewPermissionsManager() {
        return this.webViewPermissionsManager;
    }

    public List<Agent> getAgentsAllowedInCobrowse() {
        return this.getAedScreenManager().getAgentsAllowedInCobrowse();
    }

    public PermissionChecker getPermissionChecker() {
        return this.getAedScreenManager().getPermissionChecker();
    }

    private final class AssistAcitivityLifecycleCallbackHandler implements ActivityLifecycleCallbacks {
        int numOfRunning;

        private AssistAcitivityLifecycleCallbackHandler() {
            this.numOfRunning = 0;
        }

        public void onActivityCreated(Activity activity, Bundle arg1) {
            AssistCoreImpl.this.currentActivity = activity;
            Log.i(AssistCoreImpl.TAG, "onActivityCreated()");
            if (AssistCoreImpl.this.lastAssistanceConfig != null) {
                AssistAgentCobrowseListener listener = AssistCoreImpl.this.lastAssistanceConfig.getAgentCobrowseListener();
                if (listener instanceof AssistAgentCobrowseListenerDefaultImpl) {
                    ((AssistAgentCobrowseListenerDefaultImpl)listener).showDialog();
                }
            }

            AssistCoreImpl.this.initOverlayManager();
        }

        public void onActivityDestroyed(Activity arg0) {
            AssistCoreImpl.this.layoutPanWatcher.endWatch();
            (new Handler()).postDelayed(new Runnable() {
                public void run() {
                    if (AssistAcitivityLifecycleCallbackHandler.this.numOfRunning == 0) {
                    }

                    if (AssistCoreImpl.this.isAssistanceActive) {
                        AssistCoreImpl.this.overlayManager.clearAnnotations();
                    }

                    if (AssistCoreImpl.this.overlayManager.getSpotlightOverlay() != null) {
                        AssistCoreImpl.this.removeInternalListener(AssistCoreImpl.this.overlayManager.getSpotlightOverlay());
                    }

                }
            }, 100L);
        }

        public void onActivityPaused(Activity activity) {
            (new Handler()).postDelayed(new Runnable() {
                public void run() {
                    if (AssistAcitivityLifecycleCallbackHandler.this.numOfRunning == 1) {
                        AssistCoreImpl.this.overlayManager.hideOverlays();
                        AssistCoreImpl.this.isApplicationActive = false;
                        Iterator var1 = AssistCoreImpl.this.internalListeners.iterator();

                        while(var1.hasNext()) {
                            AssistInternalListener listener = (AssistInternalListener)var1.next();
                            listener.onApplicationLeft();
                        }
                    }

                    --AssistAcitivityLifecycleCallbackHandler.this.numOfRunning;
                }
            }, 100L);
        }

        public void onActivityResumed(Activity activity) {
            Log.d(AssistCoreImpl.TAG, "onActivityResumed");
            AssistCoreImpl.this.currentActivity = activity;
            AssistCoreImpl.this.isApplicationActive = true;
            View contentView = ScreenHelper.getContentView(AssistCoreImpl.this.currentActivity);
            AssistCoreImpl.this.webViewListenerManager.clearWebViewsAndListeners();
            if (contentView instanceof ViewGroup) {
                List<View> views = new ArrayList();
                ScreenHelper.getChildrenOfView((ViewGroup)contentView, views);
                Iterator var4 = views.iterator();

                while(var4.hasNext()) {
                    View view = (View)var4.next();
                    if (view instanceof WebView) {
                        WebView webView = (WebView)view;
                        AssistCoreImpl.this.webViewListenerManager.addSupportedWebView(webView);
                    }
                }
            }

            Iterator var7;
            AssistInternalListener listener;
            if (AssistCoreImpl.this.isAssistanceActive) {
                if (this.numOfRunning == 0) {
                    AssistCoreImpl.this.overlayManager.showOverlays();
                    var7 = AssistCoreImpl.this.internalListeners.iterator();

                    while(var7.hasNext()) {
                        listener = (AssistInternalListener)var7.next();
                        listener.onApplicationReturned();
                    }
                }

                AssistCoreImpl.this.overlayManager.clearAnnotations();
            }

            var7 = AssistCoreImpl.this.internalListeners.iterator();

            while(var7.hasNext()) {
                listener = (AssistInternalListener)var7.next();
                listener.onActivityChanged(AssistCoreImpl.this.currentActivity);
            }

            ++this.numOfRunning;
        }

        public void onActivitySaveInstanceState(Activity arg0, Bundle arg1) {
        }

        public void onActivityStarted(Activity arg0) {
        }

        public void onActivityStopped(Activity arg0) {
        }
    }
}
```

**Comment by caiofaustino** [comment]
Yeah so this tries to add overlays  to the screen and the 3DS2 SDK is supposed to block that for security reasons. Maybe you could ask liveassist team to give you an option to select Activities where you don't want it to run.
