### ISSUE TITLE
Fatal Exception: com.adyen.threeds2.exception.InvalidInputException Invalid challengeParameters

### ISSUE THREAD

**Issue by yohan-bittan** [Adyen/adyen-3ds2-android#40]
**Describe the bug**
Hello, we have a lot of crashes in production related to the Adyen 3DS2 SDK (for Android). The stacktrace of this crash is : 

```
Fatal Exception: com.adyen.threeds2.exception.InvalidInputException: Invalid challengeParameters.
       at atd.y.a.a(a.java:2)
       at com.adyen.threeds2.internal.i.a(i.java:11)
       at com.adyen.threeds2.internal.i.doChallenge(i.java:11)
       at com.comuto.payment.payment3ds2.challenge.navigation.ChallengeNavigatorImpl.launchChallengeScreen(ChallengeNavigatorImpl.java:34)
       at com.comuto.payment.paymentMethod.SeatCreditCardPayment.handleChallenge(SeatCreditCardPayment.java:211)
       at com.comuto.payment.paymentMethod.SeatCreditCardPayment.handleFingerprintSuccess(SeatCreditCardPayment.java:205)
       at com.comuto.payment.paymentMethod.SeatCreditCardPayment.access$handleChallengeSuccess(SeatCreditCardPayment.java:44)
       at com.comuto.payment.paymentMethod.SeatCreditCardPayment$executeFingerprint$2$2.invoke(SeatCreditCardPayment.java:195)
       at com.comuto.payment.paymentMethod.SeatCreditCardPayment$executeFingerprint$2$2.invoke(SeatCreditCardPayment.java:195)
       at com.comuto.coredomain.Either.either(Either.java:19)
       at com.comuto.payment.paymentMethod.SeatCreditCardPayment$executeFingerprint$2.invokeSuspend(SeatCreditCardPayment.java:195)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

It appears when the user has to do a 3DS2 challenge during the payment.
For information, we have integrated the version 2.2.3 of the SDK in the application.

**To Reproduce**

* Not been able to reproduce locally

**Expected behavior**
n/a

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Could you help us on this point ?
Thanks a lot

**Comment by rocklass** [comment]
Hi @caiofaustino 👋 
I work with @yohan-bittan.
We still have the same issue, even after adding the following rule in our Proguard file: `-keep class org.bouncycastle.** { *; }`

**Comment by caiofaustino** [comment]
hey there, is the issue still a `Invalid challengeParameters`?

**Comment by rocklass** [comment]
Yes there is still the same issue:
```
Fatal Exception: com.adyen.threeds2.exception.InvalidInputException: Invalid challengeParameters.
       at atd.y.a.a(a.java:2)
       at com.adyen.threeds2.internal.i.a(i.java:11)
       at **com.adyen.threeds2.internal.i.doChallenge(i.java:11)
```

**Comment by tkuntubayev** [comment]
Hey there,
Here is the same issue with more details, so we were able to find the cause:
https://github.com/Adyen/adyen-3ds2-android/issues/48

If you're facing the same problem please leave a comment there.
