### ISSUE TITLE
SDK crashes when FragmentStrictMode enabled

### ISSUE THREAD

**Issue by zsoltvilagos** [Adyen/adyen-3ds2-android#43]
**Describe the bug**

3DS2 SDK reuses some of i's internal `Fragment`s that cause the app to crash when `FragmentStrictMode`, specifically `detectFragmentReuse`, is enabled and violations are penalised by death (throwing an exception).

**To Reproduce**

1. Enable `FragmentStrictMode` for the app with `detectFragmentReuse` and `penaltyDeath`.
2. Implement the Adyen SDK for saving payment methods with custom UI, connecting to Adyen APIs via your own backend.
3. Try saving a test 3DS2 card, e.g. 5454 5454 5454 5454, 03/30, 737
4. Wait for 3DS2 Challenge
5. Complete the challenge

**Expected behavior**

Payment Method is saved, app moves on in its flow.

**Screenshots**

No screenshot.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T Pro
 - OS: 11
 - Browser: -
 - Version: -

**Additional context**

FragmentStrictMode: https://developer.android.com/reference/androidx/fragment/app/strictmode/FragmentStrictMode

Stack trace:
```
2022-02-14 14:02:14.442 20262-20262/com.example.app E/FragmentStrictMode: Policy violation with PENALTY_DEATH in com.adyen.threeds2.internal.ui.activity.c
    androidx.fragment.app.strictmode.FragmentReuseViolation: Attempting to reuse fragment c{a5af838} (f1cbfef7-bf7f-4b06-81b5-4a34f78dacb1) with previous ID 2c1537e8-5d94-4318-8444-70f0657b0448
        at androidx.fragment.app.strictmode.FragmentStrictMode.onFragmentReuse(FragmentStrictMode.kt:64)
        at androidx.fragment.app.FragmentTransaction.doAddOp(FragmentTransaction.java:299)
        at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:195)
        at androidx.fragment.app.FragmentTransaction.add(FragmentTransaction.java:224)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
        at com.adyen.threeds2.internal.ui.activity.a.i(:4)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(:20)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onNewIntent(:3)
        at android.app.Activity.performNewIntent(Activity.java:7149)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1366)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1378)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3108)
        at android.app.ActivityThread.performNewIntents(ActivityThread.java:3124)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3141)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2022-02-14 14:02:14.445 20262-20262/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 20262
    androidx.fragment.app.strictmode.FragmentReuseViolation: Attempting to reuse fragment c{a5af838} (f1cbfef7-bf7f-4b06-81b5-4a34f78dacb1) with previous ID 2c1537e8-5d94-4318-8444-70f0657b0448
        at androidx.fragment.app.strictmode.FragmentStrictMode.onFragmentReuse(FragmentStrictMode.kt:64)
        at androidx.fragment.app.FragmentTransaction.doAddOp(FragmentTransaction.java:299)
        at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:195)
        at androidx.fragment.app.FragmentTransaction.add(FragmentTransaction.java:224)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
        at com.adyen.threeds2.internal.ui.activity.a.i(:4)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(:20)
        at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onNewIntent(:3)
        at android.app.Activity.performNewIntent(Activity.java:7149)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1366)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1378)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3108)
        at android.app.ActivityThread.performNewIntents(ActivityThread.java:3124)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3141)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by caiofaustino** [comment]
Hey, sorry for the delay. Thanks for pointing this out!
I did a fix for this internally and will be added in the next release.
