### ISSUE TITLE
3DS challenge crashes during initialisation on Android 13 (targetSdkVersion 33)

### ISSUE THREAD

**Issue by Jlexyc** [Adyen/adyen-3ds2-android#45]
**Describe the bug**
We have a crash in this framework on Android 13:
```
java.lang.SecurityException: Settings key: <data_roaming> is only readable to apps with targetSdkVersion lower than or equal to: 32
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3081)
        at android.provider.Settings$Global.getStringForUser(Settings.java:15854)
        at android.provider.Settings$Global.getString(Settings.java:15837)
        at android.provider.Settings$Global.getInt(Settings.java:16078)
        at atd.s.b.b(unknown:5)
        at atd.s.b.a(unknown:1)
        at atd.h.b.a(unknown:28)
        at atd.h.b.<init>(unknown:17)
        at atd.h.b.a(unknown:3)
        at com.adyen.threeds2.internal.g.initialize(unknown:14)
        at com.adyen3ds2.Adyen3DS2Module.getTransactionParametersForIdentifyShopper(Adyen3DS2Module.kt:154)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java:-2)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:1012)
```

**To Reproduce**
Call `getTransactionParametersForIdentifyShopper` on Android 13 with sources build for targetSdkVersion 33.

**Expected behavior**
No crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android
 - Version: 13

**Additional context**
This crash only on Android 13 (with sources compiled for targetSdkVersion: 33). Also I was able to reproduce it on emulator with Android 13.

**Comment by tkuntubayev** [comment]
Hey, thank you for reporting.
It was fixed on new version 2.2.7
