### ISSUE TITLE
NullPointerException fragment isAdded

### ISSUE THREAD

**Issue by totomac** [Adyen/adyen-3ds2-android#46]
**Describe the bug**
After updating to version 2.2.7, we saw some users having this crash:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ridedott.rider/com.adyen.threeds2.internal.ui.activity.ChallengeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.Fragment.isAdded()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

**To Reproduce**
Unfortunately, we were not able to reproduce the issue

**Comment by tkuntubayev** [comment]
Hey, thank you for reporting!
We reviewed the issue and released new 2.2.8 version fixing that.
