### ISSUE TITLE
Crash on 3ds2 check (on attempt to show it) on Android 12 & Android 13.

### ISSUE THREAD

**Issue by Jlexyc** [Adyen/adyen-3ds2-android#47]
**Describe the bug**
Crash happens on 3ds2 check in 2.2.7:
```
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bolt.deliveryclient.prelive/com.adyen.threeds2.internal.ui.activity.ChallengeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.DialogFragment.isAdded()' on a null object reference
AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.DialogFragment.isAdded()' on a null object reference
AndroidRuntime: 	at com.adyen.threeds2.internal.ui.activity.a.f(:3)
AndroidRuntime: 	at com.adyen.threeds2.internal.ui.activity.a.b(:2)
AndroidRuntime: 	at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a(:25)
AndroidRuntime: 	at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onCreate(:18)
AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8057)
AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8037)
AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
```

**To Reproduce**
1. Open 3ds2 on Android (reproduced on Android 12 & Android 13).

or:
1. Open 3ds2 on Android from Activity.
2. Click Cancel on code verification screen.
3. Open 3ds2 challenge again

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 12 & Android 13
 - Version 12 & 13

**Additional context**
This happens in 100% cases.
3ds2 shows only once during app session. On second attempt it crashes (doesn't matter what the flow).
3ds2 crashes if it was opened from another Fragment on first attempt

**Comment by tkuntubayev** [comment]
Hi, thank you for a quick feedback!
We reviewed the issue and released new 2.2.8 version fixing that.
