### ISSUE TITLE
[Bug] InvalidInputException: Invalid challengeParameters

### ISSUE THREAD

**Issue by limkhashing** [Adyen/adyen-3ds2-android#48]
**Describe the bug**
Hello Adyen. We are trying to perform a 3DS2 transaction in a Production/Real environment. One of our cards - Mastercard with Issuer [Maybank](https://www.maybank.com/en/index.page) failed to do 3DS2 Challenge. 
From the SDK, it throws error
```
com.adyen.threeds2.exception.InvalidInputException: Invalid challengeParameters.
     at atd.y.a.a(:2)
     at com.adyen.threeds2.internal.i.a(:11)
     at com.adyen.threeds2.internal.i.doChallenge(:11)
     at com.kfit.fave.payment.PaymentViewViewModelImpl.performAdyenChallengeShopperFlow(PaymentViewViewModelImpl.kt:799)
     at com.kfit.fave.payment.PaymentViewViewModelImpl.handleAdyenThreeDS2ResultCode(PaymentViewViewModelImpl.kt:762)
     at com.kfit.fave.payment.PaymentViewViewModelImpl.access$handleAdyenThreeDS2ResultCode(PaymentViewViewModelImpl.kt:97)
     at com.kfit.fave.payment.PaymentViewViewModelImpl$handleAdyenThreeDS2Authentication$1.invokeSuspend(PaymentViewViewModelImpl.kt:730)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
     at android.os.Handler.handleCallback(Handler.java:938)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:233)
     at android.app.ActivityThread.main(ActivityThread.java:8068)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```
I've checked other issues on this repo, primarily this https://github.com/Adyen/adyen-3ds2-android/issues/33. Still, it doesn't help. 
What I tried and still failed to do Challenge
- Bump to latest version 2.2.8
- Use version 2.2.3

#### **Payload** (Generated from Adyen SDK with `ThreeDS2Service.INSTANCE.createTransaction().authenticationRequestParameters`)
```
{
  "messageVersion": "2.1.0",
  "sdkAppID": "4880da05-8b30-4cc0-be31-d3e3430737e5",
  "sdkEncData": "eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2Iiwia2lkIjoiM2M1ZWQzMTkwYTlhZTRiNjkyNTY2YmJmZGU3NDgzYmUyODAwMjM4OCJ9.WdyByCtkjLPIx3V1mHeYl1yPcu541TiGNFDyfQSfT0aTX-lP0-zSCx_FhfTFc8TzPUMup7mz-1zvTHhOgFL982i88N-4AezcUqy2jM-LO9qJsWDMqiqXtPCTA8xl5nYEHsGAKWZcaLVzd4ymM40xcGILQyP-Jw5QT9xQWf0a8e_fJSJjyiobRN5Ky2XSsQzjqq0cfZ-ArYF20ix_9hhIjH02-akIMY0PvdeU1qx8YaBpGJk2ZusOzKuBcwdLs7I3Gfb_j-v0g4VmgVoo7HhZ5qkUys0hrREiGg2NSXxkjWcTHuZmXS28SqBLYCwkAZq9IkRBAxAfu_NmTj2ytG1jRQ.POZ-tTghdamE2JkGS_tTBQ.HDY1BV10JyNr6u3l6hfepjz1OBFAlT6R079NTuDKbU8iQQ0zquTBfiIap8UDUjdaXj_v8nt_bjjJivAQEE9MPGhZno5faj6_feB1TbR2aL-1suFRvVM-9FY7slIHFls_ppo6WolQGMUqvMeteWEcKwnIepJzwnKMm11g1h_zO9UW1hQTRnoQ_zQl2Ww7dybw_ru-WJRbSOg_UGMIh2fyVQQCRdvDr1fNe3Vl1YQpsKxAAWQ7XIxIRg9f3oNbc7QbQAvi5PSvesIUdSAwgmmWwKH7SeyjjyIP_Qjflv4PffVxCiyQ5j1xcmjxc9F-H8W6nnlhLocWFdWGZvGzDdwUjIpsHUuuwMbOq1PvgT6tEsET4LJQNg8fm8Yb3QPqpF_eoo3D2lwYjUYZ47vl1gDcYCOu0B9QSSinnHDFAp4ZPzcZ0jO2DNgRVcum7NQ6ag7QAEW2Ca6eaY0yl0Hw-ZCf5FCi5iZ02eKh9BH2h_R_VnAv5_RkYJvtnYgtLwMbnIo2GdVx43lHY6gdFQuUfmRhZc1T3O1SGD_709OLOm7u8tp4KtoTeKoG0E1ULUH6uxEWJnUKmg8rf1fy25P0uS-zxb3917inrDDRvY5F1MVQHQ-U34DXMgWP2MJ2hseq29J5voHsVapGmGB_-8zySVbrxAkrt0UWAXDuVybmY4eEoXLn4WdKgsSmvHErnVhkonCEqtwBYQIE9yoPYStrLNvV50KFXet-nBNtRL0vj2eveZKtXFs6w5EfPyrLTguyZsWQc7oTUh_Dv9Ev39pXWYRnT9prH0ZF6FdkS0SoAuztfVkUilU-_5Er2gnjttqWBQtgZ4jZgLRcfHwCntBzH-lbIx9287vTeVio5_0dChcTVYYOQb2hjeJlf-gL0ngNyM2_eLWr5TpTRpF-LKAFs-ddDI7OY33rr_PNts48bBhi-jUmACSaPN1vQJg8SsQTto2aXkoEKtPTjbf9oy3BS8ZjYpuns3Q93ZW-VPxcaSPtefrXS01riYkqph6tSUzgjqnIc6sAGjBzK5u5cEZniTW-P5LVYXCccikYTRTkzoLo3sxmHK4aU7tNxoVcK9jZJY-sZMvg5JDbkGbcx1LyxpkEjbJPUNBjL9vE741WJOS2xEZf3IDcLxGYi82YcsCXIYe8JBfrmBSwTgjgcKFhfwO-HgE-5hWfdecXgT4ksMx2wlnl02AIbhmgps9SDsyq_u5jsG8nWQHzN3Z5k94U0VyfpqQmBARkKz10d__oU3g1hTOLFe4weOGt6oU6QH58W0whIR0VasjlpJxf9PDGBQivgGFF-MT-xyUHTpxqxGUsDNAfwxMmMk-fLp-kbQowAEe7EZVEIKW9WrRK54yQpoPfxJyd4iAgxlTStjqOyLfxrp_r4Ufh-8AY9WYwmn6LfVDk-aRuMBiZfKk4pIuPKlORgwO4kJxPT67UX8IlMrsEg5yc2kE3fQ-XdW1bvYDIJ0YFwkw_uAVyd2Ms4eUpMcS8Ge5D20YED5WqDxVYM84jyaxJBlSDRqJ4bYwRgJ0j-zVW9Cag2jSEY48evMOBMs6X-0W9W03nPTb6y-2PHd-Wsba7Lmxdd-dAAJn_bHJR1_E72JSup9RfMBlxdtP_VpBGx0oKOrZu2aGeCyD9ifyxuvZo_qvnMwhARzTCijY-d_XJSarkXGLFC2bb0qGfV05iKQ8DAXf_jOBIiJWQvg7pBOxfQR9z82INZUXiFC3lY4O-sFuugHWESrouw3vkJrlapT3CFl2DSTFKklMkxltwxLT4ZodKXggImdY9Ii4d83DkyqELeIer5s-YBX2PSM7z_Sk-TWJjdMdnLV6JSelb6Bjm-8C-dzCARlGVIEgS9o1y45rWdKZF9Pcvemd1xVxZYYOQLcz7pg-1b_iv5wzZSOHk7_v37GsFbxdkPM4movhO2uri4f5fjJrqfSNnUmFoDs2tLOXN8xFIfEXFsPkw7l6IcTRtvLnRm3HG5mdn4cIIeBioQaQvpn9T0eyh34fplwW0sVfBsV7tiNkRcBobPP-KHBnEhvTQwGf4j-QSq2O1QnATB-wwxlHbEC4J11cgDvDwknlCD2V8Y70FmAOLsh3yB5pVYCJhDrYrNbOLEtpdG8J5JlPjkTCpBHSpsWxzAlG0y4DackZNvIudp3e15Tvtoe5LCvegc-FWgFHk4K2cLILLVajSdIH0aFUrICOz6RFOdyaGDEDgDRcwMtI3d-Qdgfyvoj_hAZ50clXE-kbTOImXQJ5vH53frxWczMsgYWgYLENNjVIl3LFFfEttc_QMbi2FWojN75d7ebWnYTU-fLh1VhbPQo0gMQiWBX7CXlAf-lCjZKgCzTPQc9IQ1sOqkJ2l5EUe7rfTMroEUeGLi9qKDQeEcnlP8JCAO9F_a2L9_1NaJEKuRUgotXzdcR6MZ4uOqjCdJhdVR7gZB_Np5ZQhKSsxMibYfZHMtCozjV-ixq8R3BJGZWXwJAIfN4GlQMJOWLCTUTot3W84GcQNemF37qbmDIQ0YEsV2P2vK4RsKM59stjsVHW0bLVgx1BlrEkt5U2JNec4sy5DZHoxOStOEubrJogqi7p7pv0gY_l-a3EsqOp8y3vThqmV-SNsymhBXsmCfPrdDfvS1RVqg9Xbs5RxIiDlUIUJrl6rkHHiyWvXVpL8MuRjIUE3BJypZb15IfxgPmGJO6DzD3tTj0jZkVsgrwaSWsC1BvxiBT3uT6h3NaNa-Kji4IwEie-JXbkZRI7yj1wQvjyZTVTAOXgvM8AVNmNH54AR-wKcZTRAtbmt-ovhpTeJ1u5foYsk10L95dW7iuHHYfqYuHMm7Wcj4HWxbidE3c7uYwkci0efL1_N6KsqrGytvsY-6gXpsH0HBwJKmwuTlTDmTa3nO5CAoqs_YBj6ZPf4_5iFnIuM362HweHJMuMyIle_5ryuMhf4V9AdJ2mEI6zobpZeT8IIUDAz9v7mSoxkTOrN1pEPACNWlBxdhdwOyA_ZpvCnTPZwusoC-Q2Z7YPKt1gNBVJffLcG2H5foBTCcU6mmKWRdDJfHBg5hMuFAnADckRqxTK8h0Flu75TE9yR6u8TsLNluGm_COCU6WQnojznSabqvovyak2xvPDuNbStEPSdQ5J_L6XsiVcjzj-1ROi-hjaBRVbAWqa7F6io7ipL00WhbiL5lesIQ5PNZaAPaTjAupohOZ5NubKBbi545-LVjsEzTSloQal0lNR7tiyPmWkATtAQmNv5-8kfnStBvuEzgxlCcQdJ85qY8PDsZ3jGJ3aD0xqYnWud-N_bf6q2qzGy9lvysOGyqV-7av3clvS5_CgrzATb6Jh2VLHcDqq8LoSQd7wXkILIiaknZP8HHJcA-34avC4W53CO_tA_8ZgT6Z19i9Ar4asz9Lg1E-gGaTh5iC8RTeqwGV3Qv-iBm08CDCdXpzfv-KNdJigQU-iIEY69K-wBufG2K4nHjZsNjmRg-gRHUeSUGveXcxboTGfBYszVlm6LNyIAlyJ4zjA1sxYP71v0_0kgdkYWVtwmJXiNSAEsDMgqXT8wEWsGZwwggt8YIB4AnX05es7CENPYMmnRMwtmA65qDCa8zDZ0f4zG2ngwQxZI2qzDhpkoUYXrvEntUISEFmfXyoY-D9Vvh9wU228oBBp_JH7OOh0DrryhAouaP0KKAyLshXDAMwtoI5pkDwe09Y8ImilbJ9WwbSg5gw0Qy-fJnFBKEyUn6DK47XZMo8Z0Bkt5CkeD73RMq13qtjzeeK7wDGV-igLrjQnk1foebbC1UvyfZEV81WdzzqcAIQnoD_bNxUlj72-CDV4oblL5nijMQmDHZY3MSDwn-BJxC2TTgNjLGlZY.tzRDV3diXz9oEIbLjB2WxQ",
  "sdkEphemPubKey": {
    "crv": "P-256",
    "kty": "EC",
    "x": "WY5TazxUftFG0lF1oxe1wIh_JWmociK0jLRItYwY0BM",
    "y": "QLLPDltWoEwL8CuLxoddmfyuD3e9oq-qBjF6uxod1zc"
  },
  "sdkReferenceNumber": "3DS_LOA_SDK_ADBV_020200_00297",
  "sdkTransID": "f71c93f2-fb9a-4ed0-b983-0f46c67ab0c5",
  "threeDS2Token": "BQABAQAUiK5SQPSoHdudW/HJ4KrX801o8IC3SVgMyMMW4d9sPUwXQOhXGka9s7V5KJfqg7eIfmQ/VjQ7WG+Tg18SfctJ6+43rlqG8l7fqLHfRxrFNTFD/ULJJ/vjhDmzGLSEoimPT0DpjwlBFGZ4tBMyACpGOgstrbUeAWp5k+FlT8sPcaVxzNocpbfk4k696Wcs6vV85GgcpYw/t6d1UTA955kWN6mzq+0sRgWlmEr/KB06W83h6LyY0PR/ueUgrtk2oku/JPj70gSBLnr0aGaSoIgQtFtCqCudVJgZ6680LlkVNewm0hZE+IkSHYJiiBP2WgFvXyRLrLI6hXUDNbonKST7EO/V0ZXq9zMzTs9az1Q97KcAAE29B13gbqDz7o59Ok2XuR1lBI965709LW3Ac+FhjBnYJRRc/Ldo7qsDhWSV2mfjntsk7/VtqU7aV1pXKzjNHGgMvEl+iLrlEm0eaKtA3k1zn+n71AyxB9/BObs3aSPRGNF3h8Y8lIjLsNikw4WlxJxaQguWFw7KmAqr54VL1bB/IQo/3nCKEUv+Q8xw4/RoHTqQMAvTy6WI23eZBcfHX5TXXBS0ONWAeZqbLQlaiWIAPT3fT1pxnLoI+RBOTyayLll4uixGoXLDGevF5UAgth7uYEwJi888fYmSN448gN1TUaCbmJYkw0YzJOKjoFxNBEKcmq8kfFrV//PfwE8ipsNNDpXQMEHFjksIBQ+HEJqoaOQoHfN1dL6Tmf5XRMIaUpdfO/zN5qfFKaxRdIM9ig5GTKRoNy0VB/OMhq5jb++Iwi39tUmXFkuhp8IFOfaD3nVcd0B6OayC/skRGyTuyeXT0pfVmJCyFuz+5LlcR/OagJb5xVpcwpbuHIsJRVUIj1dSpT5GUi5cs+MAmlTIxSioEwyYJSlF+FmAD/mO6qBHy7Bxs+9cM+SAPSqr/n8rVak/CP+8fMAm8EF+XUx+MLuo6b2L3S28FewoUiWe+TV/8T2+e8Su4NpRq1/gxIjd1wHkN/dpA5OPDwKonyG3YTu8la9zerDVkF4WQQ5gB27YFQvWHue/uPNuhCsl/VDAGUpuXT19z052Hki6kE1DSHycbBj8VW3VsG4Bv59Ze4PHvO2siKGuayjoWdJGTd7Ik8VCzM2wTUjURyKMvITffx+fe+6AwGPYpDvFNwq1IJaBFj4D6GA9APGN3FFBSBT8OAKcDC27CcxGLnpisQ9fdxlQR7NEDyYpHQwAuyKH9qS9Z5Xnu3RaAOBZJ5SCX8nP4wBYONlQW+ecfqEgtI1V44ul7I1jL1GeUEjt8Ksw2mChkLAb8dv+I6ydrEwGBxsvO6WM8D0k7FW1GKiqqbixSNss8R5M9J4W1xO9hXTcXxhBF/lXelIJkfds19whz62qKfQC3WwiC/pWMuugmYIwaZFen3erq5jmGRHmiUP4b+m+wYSCvO1W6TIttPH3w0u9BapA1oA2miTaPRSLkzDlugvBhqhPEpFQY0P2oY8wbMISZOATZNrMvbh5Pm8jfLe2I+On1FCI1BwjbnmijIIhChmteDbmW2P+Knd1xiiC2mAEqV02B+ntpDjdPmTVe2obcAgA8CAG+yFvd8nFmWnbimAIC8dxC8DeVOqnkBks837VFu9InV8BDYk2QfHJY6rk/vmVTQUq7Muo1cQkxpTmu/6bZgTIKQ=="
}
```

#### Response
```
{
  "additionalData": {
    "threeds2.threeDS2ResponseData.threeDSServerTransID": "f126c0c3-482e-470a-8037-b93af131bc54",
    "cardSummary": "6567",
    "threeds2.threeDS2ResponseData.authenticationType": "02",
    "threeds2.threeDS2ResponseData.dsTransID": "5efde187-2865-439d-a4f7-fcb8615cd317",
    "cardIssuingBank": "MALAYAN BANKING BERHAD",
    "threeds2.threeDS2ResponseData.messageVersion": "2.1.0",
    "threeds2.threeDS2Token": "BQABAQAUiK5SQPSoHdudW/HJ4KrX801o8IC3SVgMyMMW4d9sPUwXQOhXGka9s7V5KJfqg7eIfmQ/VjQ7WG+Tg18SfctJ6+43rlqG8l7fqLHfRxrFNTFD/ULJJ/vjhDmzGLSEoimPT0DpjwlBFGZ4tBMyACpGOgstrbUeAWp5k+FlT8sPcaVxzNocpbfk4k696Wcs6vV85GgcpYw/t6d1UTA955kWN6mzq+0sRgWlmEr/KB06W83h6LyY0PR/ueUgrtk2oku/JPj70gSBLnr0aGaSoIgQtFtCqCudVJgZ6680LlkVNewm0hZE+IkSHYJiiBP2WgFvXyRLrLI6hXUDNbonKST7EO/V0ZXq9zMzTs9az1Q97KcAAE29B13gbqDz7o59Ok2XuR1lBI965709LW3Ac+FhjBnYJRRc/Ldo7qsDhWSV2mfjntsk7/VtqU7aV1pXKzjNHGgMvEl+iLrlEm0eaKtA3k1zn+n71AyxB9/BObs3aSPRGNF3h8Y8lIjLsNikw4WlxJxaQguWFw7KmAqr54VL1bB/IQo/3nCKEUv+Q8xw4/RoHTqQMAvTy6WI23eZBcfHX5TXXBS0ONWAeZqbLQlaiWIAPT3fT1pxnLoI+RBOTyayLll4uixGoXLDGevF5UAgth7uYEwJi888fYmSN448gN1TUaCbmJYkw0YzJOKjoFxNBEKcmq8kfFrV//PfwE8ipsNNDpXQMEHFjksIBQ+HEJqoaOQoHfN1dL6Tmf5XRMIaUpdfO/zN5qfFKaxRdIM9ig5GTKRoNy0VB/OMhq5jb++Iwi39tUmXFkuhp8IFOfaD3nVcd0B6OayC/skRGyTuyeXT0pfVmJCyFuz+5LlcR/OagJb5xVpcwpbuHIsJRVUIj1dSpT5GUi5cs+MAmlTIxSioEwyYJSlF+FmAD/mO6qBHy7Bxs+9cM+SAPSqr/n8rVak/CP+8fMAm8EF+XUx+MLuo6b2L3S28FewoUiWe+TV/8T2+e8Su4NpRq1/gxIjd1wHkN/dpA5OPDwKonyG3YTu8la9zerDVkF4WQQ5gB27YFQvWHue/uPNuhCsl/VDAGUpuXT19z052Hki6kE1DSHycbBj8VW3VsG4Bv59Ze4PHvO2siKGuayjoWdJGTd7Ik8VCzM2wTUjURyKMvITffx+fe+6AwGPYpDvFNwq1IJaBFj4D6GA9APGN3FFBSBT8OAKcDC27CcxGLnpisQ9fdxlQR7NEDyYpHQwAuyKH9qS9Z5Xnu3RaAOBZJ5SCX8nP4wBYONlQW+ecfqEgtI1V44ul7I1jL1GeUEjt8Ksw2mChkLAb8dv+I6ydrEwGBxsvO6WM8D0k7FW1GKiqqbixSNss8R5M9J4W1xO9hXTcXxhBF/lXelIJkfds19whz62qKfQC3WwiC/pWMuugmYIwaZFen3erq5jmGRHmiUP4b+m+wYSCvO1W6TIttPH3w0u9BapA1oA2miTaPRSLkzDlugvBhqhPEpFQY0P2oY8wbMISZOATZNrMvbh5Pm8jfLe2I+On1FCI1BwjbnmijIIhChmteDbmW2P+Knd1xiiC2mAEqV02B+ntpDjdPmTVe2obcAgA8CAG+yFvd8nFmWnbimAIC8dxC8DeVOqnkBks837VFu9InV8BDYk2QfHJY6rk/vmVTQUq7Muo1cQkxpTmu/6bZgTIKQ==",
    "checkout.cardAddedBrand": "mcstandarddebit",
    "threeds2.threeDS2ResponseData.acsReferenceNumber": "3DS_LOA_ACS_ISSB_020100_00062",
    "issuerCountry": "MY",
    "expiryDate": "x/xxxx", (censoring this one)
    "threeds2.threeDS2ResponseData.acsSignedContent": "eyJ4NWMiOlsiTUlJRnNUQ0NBNW1nQXdJQkFnSUlEek1MV200STJ4Z3dEUVlKS29aSWh2Y05BUUVMQlFBd2VERUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQW9UQ2sxaGMzUmxja05oY21ReEtEQW1CZ05WQkFzVEgwMWhjM1JsY2tOaGNtUWdTV1JsYm5ScGRIa2dRMmhsWTJzZ1IyVnVJRE14S2pBb0JnTlZCQU1USVZCU1JDQk5ZWE4wWlhKRFlYSmtJRE5FVXpJZ1NYTnpkV1Z5SUZOMVlpQkRRVEFlRncweU1EQXpNVGd4TVRReE1ETmFGdzB5TXpBek1UZ3hNVFF4TUROYU1JR2dNUXN3Q1FZRFZRUUdFd0pOV1RFY01Cb0dBMVVFQ0F3VFYybHNZWGxoYUNCUVpYSnpaV3QxZEhWaGJqRVZNQk1HQTFVRUJ3d01TM1ZoYkdFZ1RIVnRjSFZ5TVJBd0RnWURWUVFLREFkTllYbGlZVzVyTVNVd0l3WURWUVFMREJ4QlExTk5VeTFCUTFNdFZqSXhNQzFOUVZsQ1FVNUxMVEUwTVRNMk1TTXdJUVlEVlFRRERCcHRZM05wWjI1cGJtZHRlUzV0WVhsaVlXNXJMbU52YlM1dGVUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUk5YWRYaG9nbTFWK1VramFqNnJpZ0dmNDRxVGdtNVB6TFZXcEVwVmg4TTZEVjY3UFdHOHhzUjg3Zzc1Q2lJa0I4NVh6SWxRSWZHR0phTEVNd08xT2dwaHpGTlRRWnZycGlKeHhzZnRBWTFiRWpMMlhaVWtERkpCRFVtdDljbytZNWRYQnFLTGdJTytGbDhIa3pQNFFCdWUxdmIxS1lOUDZpMWVremNKMVgxRnBZT3lMRm9kSnJqejVpWlZqTFFtRTZEOWxDcTZrQ0JseGVxN3VpSFc4RzZwYVdPWUR6dTFwOWZ3ZzRXNDk3THlSc3htalZHbzE1Qm04MUpKVnZJSmNEczFTVmN1bGhcLzJsXC9UTFRuMFBjZmI2K2d1OHZSVENIbXdROFhFNXRrRWdKWVRQa3NwYkFNa1ZhYkE5bFFvWlk1QlRTZUNpbmhcL3ZLRTRnSDVNOHhpMENBd0VBQWFPQ0FSUXdnZ0VRTUE0R0ExVWREd0VCXC93UUVBd0lBZ0RBSkJnTlZIUk1FQWpBQU1CMEdBMVVkRGdRV0JCVFlNcmFSU2wwVXRNYkNkTGZCRFdNMUZLb2VHVEFmQmdOVkhTTUVHREFXZ0JSUDk4T2ZZc3BXVkV2ZlNIVExjQnh2UE4wUVJUQklCZ2dyQmdFRkJRY0JBUVE4TURvd09BWUlLd1lCQlFVSE1BR0dMR2gwZEhBNkx5OXZZM053TG5CcmFTNXBaR1Z1ZEdsMGVXTm9aV05yTG0xaGMzUmxjbU5oY21RdVkyOXRNR2tHQTFVZEh3UmlNR0F3WHFCY29GcUdXR2gwZEhBNkx5OWpjbXd1Y0d0cExtbGtaVzUwYVhSNVkyaGxZMnN1YldGemRHVnlZMkZ5WkM1amIyMHZOR1ptTjJNek9XWTJNbU5oTlRZMU5EUmlaR1kwT0RjMFkySTNNREZqTm1ZelkyUmtNVEEwTlM1amNtd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQzVRSGtaUTRQMU0xR215Qk9pQ0JxT284QUlaa25sRXE1WlVWSlo1eEYyVVE4alJzQWtpNEdlN0FMMzBnWTl3R3BkT1pxdUdTMndcL1d6WGdiWE9PR0syd3kycWtLS2R2ZDNIVlJLcFFrVTNSb0N0aGZlNGtcLzY3SnZpVFhKcnAzN2tEc1MrVHVSRlwvT0cxUUN4M1RRMHI4YTRxajliZDhWcEVUXC9ZVEEwNEh1aG9cL1FRRnQ3QlY4OTQxOVFIeHdobzBTTmZqSGxQZGZ3K1Rtdko3V0NXN2JNZkE1ZGJIQkZQQ0lTV2dBT0dYR0RaVnJ4eDVUOXV2RDd5TURNc25uZjdwazYrXC95a0tISDFSd3RGWXBOVjQxMjFKN3JRWmpYT2hydWlVeVVqZFBrUlNUWk95clZxYm9BS0VWSUZ5YmNiNTQ5VitlNFk4Qmt1TjNQY29iem1ZS3R1SVg4NkgrYk1jVFpvKzhcL3VPREhTMG5pMlUrelA4YlYzS2ZTRGs1bWpFK2FJem9YM2RxXC83WVcxUHc4XC9zTmdcL0J5d0xUVjl6bkFGNWVWWDZpRUd6bFBUR2c2NTlueU1nTFZmSWdiRU9aZEFpbTJLam54U1ZEUUphNlhFcmdlOUpyMEJFNldJbm9GQkR4NkpOaGtPdUxsUnNkbTBCbGd1WW0rbW5KUzhOWHd4S0pnOUVhTXBvRXV5N0RXSmF4OVJ5UHJOcW9ZV05WNXZ2UHZ1RnU1a3czdU9EaU4xZE5VVzBzdVJqODdINDBPQ3FXeWtBeE5TM0FUUHAzMjlBXC81RzFDSEtBQ1dMK3hOV0FDbTNtbm0rM1VSSmhUeWpEQlB5d1Zwem9GSjA3MjlZWjRwYVpvazJtRzJabkdQT3FQMDJJWmpRZkJxc1FSc3U1azVqSDU5XC9iWnEiXSwiYWxnIjoiUFMyNTYifQ.eyJhY3NFcGhlbVB1YktleSI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6ImFqWldWU3V4ZUhtQVk4NmFXbXlZTDF0SWZPeGwwQl9BUTNScXB2U1FSUk0iLCJ5IjoiSU5odl9qZ2wwT1ZJLXZWUVJPQmh0WTlFeHBMSDhVTy1EbUs1Z3ZTb21IMCJ9LCJzZGtFcGhlbVB1YktleSI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6IldZNVRhenhVZnRGRzBsRjFveGUxd0loX0pXbW9jaUswakxSSXRZd1kwQk0iLCJ5IjoiUUxMUERsdFdvRXdMOEN1THhvZGRtZnl1RDNlOW9xLXFCakY2dXhvZDF6YyJ9LCJhY3NVUkwiOiJodHRwczovL21heWJhbmtjYXJkc21zb3MubWF5YmFuay5jb20ubXkvSU1TMk1CQk1ZQUNTL2FwaS8zZDIvY3JlcS9hcHA_aWQ9ZEhwV00yRkRlVEpuUzNkc1R6QkZibHBtYjNoNmR6MDkifQ.Q3y4-6IhwKfPhpq4CTd6NysPJYC5ehXkqL6IMTCYsu9_ScyGhciQTQQZI76d3rnWYzXlQ2CJajeT6Hxf3X_6zOI4sQd58zw85Ezn5DafRaGLdb2dE6K_g_gQsnmB4jW1YtDnQCxCNVq3IPAjBeB2qg51mtAAuVyR1OT92D6e8mIh9wdTMt1c92nBRotEqNt-jqG60PFG1vhqH0dpGr-VaHOk4PUbQWZdMzQ7CQ4RmtMAsUxFyTsdkm40moXmIumirrGNUSIr5MPG4E-iQiOwHGujUO8K-nLESyjuZxK7UhI5Dg3k7DY_AqQnIg_J75tNS7T18Y6qDjiDRvvx0De2Qg",
    "threeds2.threeDS2ResponseData.transStatus": "C",
    "threeds2.threeDS2ResponseData.acsChallengeMandated": "Y",
    "cardBin": "549186",
    "aliasType": "Default",
    "alias": "H180203010812255",
    "recurring.shopperReference": "3872994",
    "cardPaymentMethod": "mcstandarddebit",
    "fundingSource": "DEBIT",
    "cardFunction": "Consumer",
    "threeds2.threeDS2ResponseData.acsTransID": "ce954255-18a4-42e0-a83e-ccb450e2d781",
    "issuerBin": "54918620",
    "cardIssuingCountry": "MY"
  },
  "fraudResult": {
    "accountScore": -935,
    "results": [
      {
        "FraudCheckResult": {
          "accountScore": -935,
          "checkId": -1,
          "name": "Pre-Auth-Risk-Total"
        }
      }
    ]
  },
  "pspReference": "MBP4H99RFX65Q4C2",
  "resultCode": "ChallengeShopper"
}
```
![image](https://user-images.githubusercontent.com/30791939/193304078-bf306204-eda8-4232-bfb8-884e95717138.png)
![image](https://user-images.githubusercontent.com/30791939/193334084-9a6e1d32-e239-482f-b0a9-93ab77ec71f1.png)

**The first Adyen API response that we received, before we proceed calling Adyen 3DS2 API**
![image](https://user-images.githubusercontent.com/30791939/193303981-31136249-542e-41bb-9842-25946ff83406.png)

**Expected behavior**
Should go to ChallengeActivity from Adyen SDK

**Screenshots**
![image](https://user-images.githubusercontent.com/30791939/193303820-f84e5d97-8650-4497-85c4-8cf5cfaca3d1.png)

**Smartphone (please complete the following information):**
Android OnePlus 6. Android version 11

**Additional context**
Note that all other cards from other Issuers are working fine. For example, VISA with Maybank.

**Comment by tkuntubayev** [comment]
Hi, thank you for providing details.
Does it happen only with Mastercard cards of Maybank? Does it work with Mastercard cards from other issuers?
Are you facing the same problem on iOS?

**Comment by limkhashing** [comment]
@tkuntubayev Thanks for replying! Yes, it only happens with Mastercard cards of Maybank. Other Mastercard cards from other issuers are working fine

For iOS, we are facing different errors `secure channel setup failed`. Sadly I don't have the logs with me since it's handled by different iOS engineers. 

We cross-checked with other issues on iOS repo. Still doesn't help much
https://github.com/Adyen/adyen-3ds2-ios/issues/26
https://github.com/Adyen/adyen-ios/issues/730

**Comment by tkuntubayev** [comment]
Hey @limkhashing,
From the provided network logs it seems that "threeds2.threeDS2ResponseData.acsSignedContent" field which is coming from the issuer's ACS is not signed with the correct directory server certificate. We will contact the issuer bank through Mastercard to clarify that.
Thanks for sharing, hope it will help.

**Comment by limkhashing** [comment]
Hello @tkuntubayev . I understand this is 8 months old, but just wanted to check with you are there any updates from Mastercard or the issuer bank regarding this issue?

**Comment by tkuntubayev** [comment]
Hello @limkhashing,
We had contacted Maybank informing them about the issue. From the latest update they were working on a fix, but we didn't receive any final result from them after it. Let me check if they have any estimation date on the fix release.

**Comment by limkhashing** [comment]
@tkuntubayev  Nice thanks! Please let me know again if there are any further updates 🙏 appreciate it

**Comment by limkhashing** [comment]
@tkuntubayev Hello, sorry to bug you again. But may I know whether they have any updates or the issue is resolve?

Also just wondering, is it possible to loop me into the email that informed Maybank about this issue? My email is kha.shing@myfave.com

**Comment by tkuntubayev** [comment]
@limkhashing on 4th of July Maybank informed that the new certificates were released. Which means that now app flow transactions should work correctly.

**Comment by limkhashing** [comment]
@tkuntubayev I see. That's great to hear! Thank you very much for helping follow up with them. 

I will let my team know and re-test the transaction with Maybank's Mastercard 🙏 and will let you know again if any issues happen

**Comment by limkhashing** [comment]
Hello @fdcb Unfortunately we didn't manage to test it yet, since we are short of capacity/resources at the moment. Will let you know again if we tested it
