### ISSUE TITLE
Fatal Exception: com.adyen.threeds2.exception.SDKRuntimeException: Challenge presentation failure.

### ISSUE THREAD

**Issue by mikkoville** [Adyen/adyen-3ds2-android#58]
**Describe the bug**
We are seeing the following crashes coming from Adyen SDK crashing our application:

```
Fatal Exception: com.adyen.threeds2.exception.SDKRuntimeException: Challenge presentation failure.
       at atd.a0.c.a(c.java:2)
       at atd.a0.c.a(c.java:1)
       at com.adyen.threeds2.internal.i.c(i.java:2)
       at com.adyen.threeds2.internal.i.protocolError(i.java:3)
       at com.adyen.threeds2.internal.f.a(f.java:130)
       at com.adyen.threeds2.internal.f$d.a(f.java:1)
       at com.adyen.threeds2.internal.f$d.accept(f.java:1)
       at com.adyen.threeds2.internal.f.a(f.java:44)
       at com.adyen.threeds2.internal.f.a(f.java:21)
       at atd.a.d$b.run(d.java:1)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

This is happening on sdk version 2.2.15 & also previous 2.2.x versions

**To Reproduce**
- No info how to reproduce since we are catching these from production

**Expected behavior**
- Should not crash the application

**Smartphone (please complete the following information):**
 - Device: Multiple devices like Samsung Galaxy a23, Galaxy s22/ultra, Xiamoi redmi note 9, Oneplus nord ce2, 
 - OS: 13, 12, 11, 10

**Additional context**

From the public Adyen sdk api we can see `SDKRuntimeException` might be thrown by:
- `ThreeDS2Service.INSTANCE.initialize()`
- `ThreeDS2Service.INSTANCE.createTransaction()`

`We are calling **both** above calls inside a try catch so they should not crash our application. This must be thrown from somewhere else

Note that we are calling **Transaction.doChallenge()** also wrapped in try catch so it should not be thrown from here either

**Comment by tkuntubayev** [comment]
Hi @mikkoville,
Thank you for reporting the issue! Our team will investigate it further and come back soon.

**Comment by fdcb** [comment]
Hi @mikkoville we have not been able to reproduce your issue. Are you still experiencing this issue?

**Comment by mikkoville** [comment]
@fdcb It seems to happen quite rarely. Only 2 times in last 90 days but seems it is still possible.

**Comment by tkuntubayev** [comment]
Closing this due to inactivity. Please reopen if you still encounter this issue in the latest version.
