### ISSUE TITLE
Conflict with firebase-perf plugin

### ISSUE THREAD

**Issue by shchurov** [Adyen/adyen-3ds2-android#6]
Whenever I try to build my project including adyen-3ds2 dependency I'm getting an error:
```
AGPBI: {"kind":"warning","text":"Methods with invalid locals information:\n  boolean com.google.zxing.qrcode.detector.FinderPatternFinder.foundPatternCross(int[])\n  Attempt to define local of type int as moduleSize","sources":[{"file":".../FirebasePerformancePlugin/master/debug/141/com/google/zxing/qrcode/detector/FinderPatternFinder.class"}],"tool":"D8"}
```

Seems to be a conflict with Firebase Perf. If I remove the following line from my build.gradle script it also builds fine: `apply plugin: 'com.google.firebase.firebase-perf'`

I'm using the latest versions of Firebase Perf taken from here:
https://firebase.google.com/docs/perf-mon/get-started-android#step_1_add_to_your_app

**Comment by ran-haveshush** [comment]
Hi @shchurov, it is probably related to differences in dependencies versions.
Can you please follow the [resolve dependencies solution](https://github.com/Adyen/adyen-3ds2-android/blob/master/TROUBLESHOOTING.md#the-app-fails-to-build-when-integrating-the-sdk).

Please update me on the results.

**Comment by shchurov** [comment]
Tried both options, it didn't help. I was able to build the project in the end using:
`android.enableD8.desugaring=false` in gradle.properties (which is an experimental feature).

Although it works, it doesn't feel like a reliable long-term solution. So can you continue the investigation on your side?

**Comment by ran-haveshush** [comment]
@shchurov thanks for the update.

We need more info on your project build and dependencies in order to reproduce the issue.
- Gradle version.
- Android gradle plugin version.
- Gradle properties.
- Android build tools version.

**Comment by shchurov** [comment]
Sure,
- Gradle: 5.1.1
- Android gradle plugin: 3.4.1
- Build tools: tried 28.0.3 and 29.0.0-rc3

gradle.properties:
```
org.gradle.daemon=true
org.gradle.jvmargs=-Xms2048m -Xmx4096M -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true
#android.enableD8.desugaring=false
```

**Comment by ran-haveshush** [comment]
Hi @shchurov,

I wasn't able to reproduce the build issue with the below setup:

* Android Studio 3.4.1
* Gradle: 5.1.1
* Android gradle plugin: 3.4.1
* Build tools: 28.0.3
* min_sdk: 16
* Target SDK: 28
* Compile SDK: 28
* Support library dependency: 26.1.0
* Firebase pref plugin: com.google.firebase:perf-plugin:1.2.1
* Firebase dependency: com.google.firebase:firebase-perf:17.0.2
* Adyen 3DS2 SDK dependency: com.adyen.threeds:adyen-3ds2:0.9.6

Gradle properties:
`org.gradle.daemon=true
org.gradle.jvmargs=-Xms2048m -Xmx4096M -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true`

Is it different from your setup?

If you would like, we can have an online session to solve the build issue.

Cheers,
Ran

**Comment by shchurov** [comment]
My support library version is 28.0.0, looks the same otherwise.
After some investigation I started thinking that it can be related to R8. 
It builds if I set `minifyEnabled true`.

**Comment by ran-haveshush** [comment]
Regarding the support library version the project builds fine with version 28.0.0.

Not something important:
-dontwarn org.bouncycastle.**
-dontwarn com.adyen.threeds2.**

In order to suppress D8 warnings that we are aware of.

**Comment by ran-haveshush** [comment]
Hi @shchurov Is there anything we can do on our side?

**Comment by shchurov** [comment]
My main suspect atm is some sort of stripping/obfuscation because the project builds if I set `minifyEnabled true`. I'll continue the investigation on my side and then will get back to you.

**Comment by ran-haveshush** [comment]
@shchurov but if the module build type minifyEnabled is set to true then code shrinking and obfuscation are enabled. According to that the project builds fine with code shrinking and obfuscation so it should also build fine without it.

**Comment by shchurov** [comment]
That's my idea as well, nevertheless it only builds with minifyEnabled 🤔

**Comment by shchurov** [comment]
Hi, I made a small test project that has the same issue. Can you try it? 
https://drive.google.com/file/d/1PQsYzswNaxNPedBDCfp2DsbMMZ4xfaRX/view?usp=sharing

Also we noticed that it doesn't build on macos but does on linux 🤷‍♂

**Comment by ran-haveshush** [comment]
Hi @shchurov,

Sure, thanks for the test project.
i'll test it on my Mac and update you.

**Comment by shchurov** [comment]
Hi @ran-haveshush, any updates?

**Comment by ran-haveshush** [comment]
Hi @shchurov, 

The TestProject that you shared build just fine.

BTW: you should import the the dependency with `implementation` and not with `api` like so:
implementation "com.adyen.threeds:adyen-3ds2:0.9.6"
Not that it will make a difference to build issue.

Can you share the TestProject build error?

Cheers,
Ran

**Comment by shchurov** [comment]
here's the full output
```
➜  TestProject ./gradlew assembleDebug
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/c/b/b/c.class: D8: Type `a.a.a.s` was not found, it is required for default or static interface methods desugaring of `java.security.PrivateKey a.a.f.c.b.b.c.engineGeneratePrivate(java.security.spec.KeySpec)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/com/adyen/threeds2/internal/c/a/c/h.class: D8: Type `com.google.android.gms.tasks.Tasks` was not found, it is required for default or static interface methods desugaring of `android.location.Location com.adyen.threeds2.internal.c.a.c.h.a(android.content.Context)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/h.class: D8: Type `a.a.a.k` was not found, it is required for default or static interface methods desugaring of `void a.a.f.a.h.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/h.class: D8: Type `a.a.a.t` was not found, it is required for default or static interface methods desugaring of `a.a.f.a.h a.a.f.a.h.a(java.lang.Object)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/l.class: D8: Type `a.a.a.o` was not found, it is required for default or static interface methods desugaring of `void a.a.f.a.l.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/l.class: D8: Type `a.a.a.z` was not found, it is required for default or static interface methods desugaring of `void a.a.f.a.l.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/d.class: D8: Type `a.a.a.t` was not found, it is required for default or static interface methods desugaring of `a.a.f.a.d a.a.f.a.d.a(java.lang.Object)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/a/e/a.class: D8: Type `a.a.a.n` was not found, it is required for default or static interface methods desugaring of `void a.a.a.e.a.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/c/b/f/f.class: D8: Type `a.a.a.s` was not found, it is required for default or static interface methods desugaring of `java.security.PrivateKey a.a.f.c.b.f.f.engineGeneratePrivate(java.security.spec.KeySpec)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/c/b/d/c.class: D8: Type `a.a.a.s` was not found, it is required for default or static interface methods desugaring of `java.security.PrivateKey a.a.f.c.b.d.c.engineGeneratePrivate(java.security.spec.KeySpec)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/b/e/z.class: D8: Type `a.a.f.b.e.e` was not found, it is required for default or static interface methods desugaring of `void a.a.f.b.e.z.<init>(int, a.a.b.g)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/b/e/r.class: D8: Type `a.a.f.b.e.d` was not found, it is required for default or static interface methods desugaring of `void a.a.f.b.e.r.<init>(int, int, a.a.b.g)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/c/b/b/a.class: D8: Type `a.a.a.o` was not found, it is required for default or static interface methods desugaring of `void a.a.f.c.b.b.a.<init>(a.a.a.d.b)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/c.class: D8: Type `a.a.a.t` was not found, it is required for default or static interface methods desugaring of `a.a.f.a.c a.a.f.a.c.a(java.lang.Object)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/a/d/b.class: D8: Type `a.a.a.v` was not found, it is required for default or static interface methods desugaring of `void a.a.a.d.b.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/g.class: D8: Type `a.a.a.k` was not found, it is required for default or static interface methods desugaring of `void a.a.f.a.g.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/g.class: D8: Type `a.a.a.o` was not found, it is required for default or static interface methods desugaring of `void a.a.f.a.g.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/f/a/i.class: D8: Type `a.a.a.k` was not found, it is required for default or static interface methods desugaring of `void a.a.f.a.i.<init>(a.a.a.t)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/com/adyen/threeds2/internal/c/a/c/a.class: D8: Type `com.google.android.gms.ads.identifier.AdvertisingIdClient` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.adyen.threeds2.internal.c.a.c.a.a(android.content.Context)`
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/com/adyen/threeds2/internal/a/b.class: D8: Type `com.google.firebase.perf.network.FirebasePerfUrlConnection` was not found, it is required for default or static interface methods desugaring of `java.net.HttpURLConnection com.adyen.threeds2.internal.a.b.a(java.lang.String)`
D8: Class content provided for type descriptor a.a.a.Da actually defines class a.a.a.da
D8: Class content provided for type descriptor a.a.a.Da actually defines class a.a.a.da
D8: Class content provided for type descriptor a.a.a.Da actually defines class a.a.a.da
/Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0/a/a/a/q$a.class: D8: Type `a.a.a.q` was not found, it is required for default or static interface methods desugaring of `void a.a.a.q$a.a(int)`
D8: Class content provided for type descriptor a.a.a.A actually defines class a.a.a.a

> Task :app:transformClassesWithDexBuilderForDebug
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
        at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:149)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:420)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:47)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at java.util.Optional.map(Optional.java:215)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
        at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/mike/dev/android/projects/TestProject/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/0
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:909)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
        at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:904)
        ... 6 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:81)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
        at com.android.tools.r8.D8.run(D8.java:94)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
        ... 7 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Class content provided for type descriptor a.a.a.Da actually defines class a.a.a.da
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:101)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:72)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:66)
        ... 10 more
```

**Comment by ran-haveshush** [comment]
@shchurov, it seems like we have different gradle properties. 

Gradle looks for gradle.properties files in these places:

* in project build dir (that is where your build script is) (should be the same since it is in TestProject)
* in sub-project dir (should be the same since it is in TestProject)
* in gradle user home (defined by the GRADLE_USER_HOME environment variable, which if not set defaults to USER_HOME/.gradle)

Properties from one file will override the properties from the previous ones (so file in gradle user home has precedence over the others, and file in sub-project has precedence over the one in project root).

Do you have another gradle.properties file under your user directory?

**Comment by shchurov** [comment]
Just checked, I don't have gradle.properties file in USER_HOME./gradle
Also, we tested it on 4 different laptops with different setups. It didn't work on any of macbooks but worked on linux.

**Comment by shchurov** [comment]
btw, if it helps, test project builds if I remove `compileOptions` (related to java 8) or `multiDexEnabled` from the gradle script

**Comment by ran-haveshush** [comment]
Sorry I couldn't reproduce the provided TestProject build issues on our macbooks, seems like a gradle configuration issue on your machines which influence not just the SDK but also the Firebase plugin.

**Comment by shchurov** [comment]
Can it be something similar to this?
https://github.com/google-ar/arcore-android-sdk/issues/644#issuecomment-438455164
Because this error looks case-sensitive related:
`Caused by: com.android.tools.r8.utils.AbortException: Error: Class content provided for type descriptor a.a.a.Da actually defines class a.a.a.da`

**Comment by shchurov** [comment]
@ran-haveshush Did you have a chance to look into it?

**Comment by ran-haveshush** [comment]
@shchurov thanks for the tip,

I'll try that and provide you with a test sdk.

Cheers,
Ran

**Comment by ran-haveshush** [comment]
@shchurov sent you a test SDK.
Please update me on the matter.

**Comment by shchurov** [comment]
@ran-haveshush Sorry, I don't see it anywhere. Can you clarify where you sent it?
Best way to reach me is at mike@wolt.com

**Comment by ran-haveshush** [comment]
@shchurov sent it the above mentioned email, did you receive it?

**Comment by shchurov** [comment]
Yes, unfortunately, I see a very similar error. 
`com.android.tools.r8.utils.AbortException: Error: Class content provided for type descriptor c.a.f.b.e.E actually defines class c.a.f.b.e.e`
Can you double-check that `-dontusemixedcaseclassnames` is included to the sdk proguard rules before obfuscating it?

**Comment by shchurov** [comment]
Btw, here's another similar issue https://stackoverflow.com/questions/51415603/android-firebaseperformance-issue-with-proguard

**Comment by ran-haveshush** [comment]
We are using R8 as the code shrinker, it looks like [Google R8 is ignoring the -dontusemixedcaseclassnames property]( https://r8.googlesource.com/r8/+/b72b7437aad013c6f16c7ea97c1687b846679f37/src/main/java/com/android/tools/r8/shaking/ProguardConfigurationParser.java#59 ).

We are looking for a fix, will update you...

**Comment by ran-haveshush** [comment]
Seems like there should be a fix for it, at least by this [tracked issue](https://issuetracker.google.com/issues/129493704).

**Comment by shchurov** [comment]
It works ok now with the latest AAR you sent me 👍
