### ISSUE TITLE
AppUpgradeBroadcastReceiver.onReceive -  java.lang.NoSuchMethodError - No static method a(J)Ljava/lang/String; in class Latd/x0/a; or its super classes

### ISSUE THREAD

**Issue by anthonymonori** [Adyen/adyen-3ds2-android#66]
**Describe the bug**
```
Fatal Exception: java.lang.NoSuchMethodError: No static method a(J)Ljava/lang/String; in class Latd/x0/a; or its super classes (declaration of 'atd.x0.a' appears in /data/app/~~RADlBsF9szpiEKGdOOajzg==/com.transferwise.android-hXNdWaJGCg595QoG0AyFsQ==/base.apk)
       at com.adyen.threeds2.internal.AppUpgradeBroadcastReceiver.onReceive(AppUpgradeBroadcastReceiver.java:1)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4663)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2357)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**To Reproduce**
We observed the above crash coming from one customers using the 2.2.15 version of the SDK. We were not able to reproduce it locally.

**Expected behavior**
To understand better what caused the crash

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 14

**Comment by anthonymonori** [comment]
I can see in the latest [2.2.16](https://github.com/Adyen/adyen-3ds2-android/releases/tag/2.2.16) now sets both `compileSdkVersion` and `targetSdkVersion` to 34 (Android 14) which could theoretically have an impact on the above. I'll try to update next week, but if you can take a look at the stack trace and confirm that it is the same issue, feel free to close this already.

**Comment by anthonymonori** [comment]
Sorry for the radio silence, I haven't seen the issue again after the upgrade, so it looks to be fixed.
