### ISSUE TITLE
java.lang.NoSuchMethodError: No super method destroy()V in class Ljavax/crypto/spec/SecretKeySpec;

### ISSUE THREAD

**Issue by rodrigodias** [Adyen/adyen-3ds2-android#69]
**Describe the bug**
```
java.lang.NoSuchMethodError: No super method destroy()V in class Ljavax/crypto/spec/SecretKeySpec; or its super classes (declaration of 'javax.crypto.spec.SecretKeySpec' appears in /system/framework/core-oj.jar)
    at com.adyen.threeds2.internal.jose.jwa.contentencryption.ContentEncryptionKey.destroy(:50)
    at com.adyen.threeds2.internal.jose.jwe.CryptoContext.destroy(:62)
    at com.adyen.threeds2.internal.cancel.nextFloat(:77)
    at com.adyen.threeds2.internal.cancel.cancel(:1)
    at com.adyen.threeds2.internal.CipherOutputStreamF2200.cancel(:283)
    at com.adyen.threeds2.internal.CipherOutputStreamF2200.createTransaction(:155)
    at com.enterprise.activity.PaymentActivity$3.run(BasePaymentActivity.java:1011)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

**To Reproduce**
1 - Customers with Android 7 (api 25) and below with the Adyen SDK version 2.2.17 and 2.2.18. 
2 - Occurs when start of Challenge flow;

**Expected behavior**
Start Challenge flow;

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 7,6,5
 - Version 25,24,23,22,21

**Additional context**

**Comment by tkuntubayev** [comment]
Hi @rodrigodias,
Thank you for sharing this!
We will examine the issue and provide updates here soon.

**Comment by tkuntubayev** [comment]
The new 2.2.19 SDK version that addresses the issue has been released.  @rodrigodias thanks again for reporting this!
